### ISSUE TITLE
sourcedirs.rs panics after upgrading from v1.0.4 to 1.0.5

### ISSUE THREAD

**Issue by vasco3** [teamwalnut/rewatch#108]
run rewatch clean and rewatch watch. Then i see the following error

```
> pnpm rewatch watch . 

[1/7] 📦 Built package tree in 0.00s
[2/7] 🕵️  Found source files in 0.00s
[3/7] 📝 Read compile state 0.00s
[4/7] 🧹 Cleaned 0/0 0.00s
[5/7] 🧱 Parsed 120 source files in 0.14s
[6/7] ️🌴 Collected deps in 0.00s
[7/7] 🤺 ️Compiling... ⠂ 122/122                                                        thread 'thread '<unnamed><unnamed>' panicked at src/sourcedirs.rs:26:10:
called `Result::unwrap()` on an `Err` value: StripPrefixError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
' panicked at src/sourcedirs.rs:26:10:
called `Result::unwrap()` on an `Err` value: StripPrefixError(())
 ELIFECYCLE  Command failed with exit code 101.
```

I rolled back and it works fine again.

**dependencies**
- `"@rescript/react": "^0.12.1",`
- ` "rescript": "11.1.0",`

**Comment by rolandpeelen** [comment]
Will have a look into this.

Can you run it with a backtrace with any chance? `RUST_BACKTRACE=1` ?

**Comment by rolandpeelen** [comment]
@vasco3 - Made this optional for now: https://github.com/teamwalnut/rewatch/releases/tag/v1.0.6 -- Release is building.

But - would love to work on fixing this. It looks to me like the path of the package it's trying to resolve is a sub path of another package. Are you able to build Rewatch from source? Ie - If I prepare a branch for you with some debug statements, would you be able to compile it and run it on your repo so we get some debug information?

**Comment by vasco3** [comment]
> `RUST_BACKTRACE=1`

like this? (v1.0.6)
<img width="309" alt="image" src="https://github.com/teamwalnut/rewatch/assets/804301/b49fcfee-646a-4b90-84d9-3fa7943831b2">

**Comment by rolandpeelen** [comment]
Yeah, could be that this doesn't work in release mode. But let's try:
1. `pnpm rewatch clean .` - clean state
2. `RUST_BACKTRACE=1 pnpm rewatch build .` (this should then spawn the error and hopefully give us a backtrace).

If it doesn't I'll try and prepare a build for you that you can install which will have some more debug info.

**Comment by rolandpeelen** [comment]
Hey! Yes, we made them optional. Sorry, should have included the tag. So;

1. `pnpm rewatch clean . - clean state`
2. `RUST_BACKTRACE=1 pnpm rewatch --create-sourcedirs true build .`

**Comment by vasco3** [comment]
@rolandpeelen 
here is the result

![CleanShot 2024-05-07 at 14 04 25@2x](https://github.com/teamwalnut/rewatch/assets/804301/85a892e1-f6ab-4075-a7c4-00f7465fb33c)

**Comment by vasco3** [comment]
running with full
![CleanShot 2024-05-07 at 14 06 40@2x](https://github.com/teamwalnut/rewatch/assets/804301/982192ca-9a55-4d84-8a5f-c1e762d18065)

**Comment by rolandpeelen** [comment]
Awesome. Thank you! 
Ok. there is not that much info there unfortunately. Would you happen to have you have a small public github repo that reproduces this issue?

Alternatively, I can build you a version of Rewatch that does some more logging. But not sure when I can get to that

**Comment by vasco3** [comment]
@rolandpeelen yeah I'll put together a repro repo soon

**Comment by vasco3** [comment]
@rolandpeelen good news, 
The sourcedirs error happens when I add `@rescript/react` 

here is the minimal repo
https://github.com/vasco3/rewatch-pnpm
